### ISSUE TITLE
feature 

### ISSUE THREAD

**Issue by 0bvim** [x3ric/octobot#1]
Hello dear! First, congrats for this script. Good Job!

You can consider add unfollow with exceptions. If you wanna keep some account that probably will not follow you back for enterprise or any that you want in a file ou a env var or something like. 

I'm considering write your script in golang, what you think about? I really like of your project!

**Comment by x3ric** [comment]
Hi 0bvim,

Thank you for your feedback! I appreciate your positive remarks about the project and your ideas.

The blacklist feature was indeed planned but hasn't been developed yet. I'll be working on it today and will push the update if completed. Porting to Go is an excellent suggestion, so feel free to proceed with your fork as you see fit. The main branch will remain in Bash due to its compactness, ease of use, and customizability.

I’m excited about your interest in contributing and fully support your fork. I truly appreciate your efforts!

Best regards,  
x3ric

**Comment by 0bvim** [comment]
Oh, very nice bro!
I was afraid you wouldn't like it. I'm happy that you appreciate!

Best regards,
0bvim!
